language: r
warnings_are_errors: true
apt_packages:
- libudunits2-dev
- libnetcdf-dev
r_github_packages:
- sgibb/MALDIquant
- sgibb/MALDIquantForeign
r_binary_packages:
- testthat
- knitr
- XML
- base64enc
- digest
- sda
- pvclust
- xtable
notifications:
  email:
    on_success: change
    on_failure: change
