language: r
sudo: false
cache: packages
warnings_are_errors: true
addon:
  apt:
    packages:
      - libudunits2-dev
      - libnetcdf-dev

r:
#  - oldrel
  - release
  - devel

notifications:
  email:
    on_success: change
    on_failure: change
