## This is a MALDIquant example file. It is released into public domain with the
## right to use it for any purpose but without any warranty.

## This example file demonstrates using MALDIquant to analyze data generated by
## a Direct Infusion/Orbitrap MS device (DIMS).

## A lof of thanks to Victor Nesati <lsivn@nus.edu.sg> for sharing the workflow
## and providing the example data set.

## load libraries
library("MALDIquant")
library("MALDIquantForeign")

## import mzXML data
spectra <- import("http://files.figshare.com/1106533/Example.zip")

## averaging individual scans into a mean spectrum per file
files <- sapply(spectra, function(x)metaData(x)$file)
meanSpectra <- averageMassSpectra(spectra, files)

## peak detection
peaks <- detectPeaks(meanSpectra, halfWindowSize=4, SNR=0)

## determine warping functions without lock mass
pdf("warpingplots.pdf")
warpingFunctions <- determineWarpingFunctions(peaks, tolerance=4e-6,
                                              plot=TRUE)
dev.off()

## alternatively: determine warping functions with lock mass
referencePeaks <- createMassPeaks(mass=c(277.1048, 536.1654, 593.157612,
                                         610.1842, 667.176404, 684.20295),
                                  intensity=rep(1, 6))
pdf("warpingplotsREF.pdf")
warpingFunctions <- determineWarpingFunctions(peaks, reference=referencePeaks,
                                              plot=TRUE)
dev.off()

## apply warping functions
warpedPeaks <- warpMassPeaks(peaks, warpingFunctions)

## peak binning
binnedPeaks <- binPeaks(warpedPeaks, tolerance=4e-6)

## peak filtering (removal of features occurring in less than 1/3 of all
## spectra)
filteredPeaks <- filterPeaks(binnedPeaks, minFrequency=1/3)

## create feature matrix
featureMatrix <- intensityMatrix(filteredPeaks)

## fetch names from filenames
groups <- sapply(peaks, function(x)substr(basename(metaData(x)$file), 1, 12))
rownames(featureMatrix) <- groups

## save to CSV file
write.csv(featureMatrix, file="featureMatrix.csv")

