<<knitrsetup_library, include=FALSE, cache=FALSE>>=
library("knitr")
opts_knit$set(self.contained=FALSE)
@

First we have to load the packages.
<<loadpackages, echo=FALSE>>=
suppressPackageStartupMessages(library("MALDIquantExamples"))
@
<<packages>>=
## the main MALDIquant package
library("MALDIquant")
## the import/export routines for MALDIquant
library("MALDIquantForeign")

## example data
library("MALDIquantExamples")
@
